### ISSUE TITLE
Add option `left to right direction`

### ISSUE THREAD

**Issue by VladimirAlexiev** [VladimirAlexiev/rdf2rml#18]
@mariapoveda, @rgcmme
I made a diagram from one of your examples: 
![](https://github.com/VladimirAlexiev/rdf2rml/raw/master/test/saref4city/example1-saref4city.png)

Details in https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/saref4city.
Had to tweak prefixes and base to make it look better.
If there's interest to visualize other SAREF examples like this, we can automate it.

---

https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/saref4city#why-the-rigmarole:
need to add option `left to right direction` to my tool.

Maybe something like this in Turtle
```ttl
[] puml:option "left to right direction"
```
where the text is directly dumped at the beginning of the puml.

Pros of this simple approach:
- This will also handle `skinparam` and `!pragma`
- "left to right direction" is neither skinparam, nor pragma (https://forum.plantuml.net/17002/how-to-set-left-to-right-direction-from-command-line) so needs to be emitted as text.
- cons: the textual order of statements `puml:option` is not guaranteed, but some puml options may need to come in order
- but hey! the user can use a multiline string like this:
```ttl
[] puml:option """
left to right direction
!pragma layout smetana
"""
```

**Comment by mariapoveda** [comment]
This looks really good. Which is the tool to generate the graphics?

**Comment by rgcmme** [comment]
Yes, it is very nice!

**Comment by VladimirAlexiev** [comment]
@mariapoveda @rgcmme The tool is `rdfpuml` in this repo
