### ISSUE TITLE
remove Carp::Always

### ISSUE THREAD

**Issue by VladimirAlexiev** [VladimirAlexiev/rdf2rml#2]
With `use strict; use warnings; use autodie;` 
I don't think we need `use Carp::Always` (http://search.cpan.org/~ferreira/Carp-Always-0.13/lib/Carp/Always.pm). It'll show a stack trace on every die but who needs this for a missing file?

cc @jonassmedegaard

**Comment by jonassmedegaard** [comment]
It seems to me that Carp::Always is useful only for developers - I don't see a need for stacktraces exposed to end-users.

So if you ask me, then I agree Carp::Always is unneeded.
