### ISSUE TITLE
PNG output is truncated

### ISSUE THREAD

**Issue by saxomoose** [VladimirAlexiev/rdf2rml#29]
Thank you for open-sourcing this tool, including the containerized image.

I am trying to visualize graphs from the domain `data.vlaanderen.be`. An example of input is `https://data.vlaanderen.be/ns/persoon.ttl`. This turtle file does not contain any `puml:` term. I am just trying to see what the visualization looks like without any configuration.

I run  `docker run -v <directory>:/files --rm docker-registry.ontotext.com/rdf2rml:latest`.

Here is the png output which is truncated.

![persoon](https://github.com/VladimirAlexiev/rdf2rml/assets/52952423/bcb97cd1-1674-400e-b2b2-e2e96a057cfa)

How can I prevent the truncation?

**Comment by atacanavgoren** [comment]
Hi may I ask Could you find a solution for this problem?

**Comment by saxomoose** [comment]
No I didn't find a solution. Do you have a recommendation?

**Comment by VladimirAlexiev** [comment]
hi @saxomoose , @atacanavgoren!
See something better in https://github.com/VladimirAlexiev/rdf2rml/tree/master/test/vlaanderen but:
- if you expect to shove a sloppily defined ontology to this tool and obtain Enlightenment, you are mistaken
- the tool is not intended to visualize whole ontologies but carefully prepared subsets or examples

If you have some ideas how to produce more clear diagrams, please let me know (and reopen this if appropriate).
But "more clear" is not the same as "I need a bigger sheet of paper" !!!
